name: Update Documentation

on:
  push:
    paths:
      - "README.md"   # спрацьовує лише коли змінюється README.md

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown

      - name: Generate HTML documentation
        run: |
          python generate_docs.py

      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git commit -m "Auto-update HTML documentation"
          git push